"""Add deleted_at to shools

Revision ID: 59f6ee8ff1bb
Revises: e15d909a9c0e
Create Date: 2026-01-26 16:36:16.280962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f6ee8ff1bb'
down_revision = 'e15d909a9c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('class_grade', sa.Enum('FISRT_YEAR', 'SECOND_YEAR', 'THIRD_YEAR', name='classgrade'), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    op.drop_table('school_classes')
    # ### end Alembic commands ###
