"""Add BigInteger type to school_id

Revision ID: e15d909a9c0e
Revises: 48c79a674166
Create Date: 2025-12-20 22:52:49.175666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e15d909a9c0e'
down_revision = '48c79a674166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_type', sa.Enum('federal', 'estadual', 'municipal', 'privada', name='school_type_enum'), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('federal', 'estadual', 'municipal', 'privada', name='school_type_enum'), autoincrement=False, nullable=False))
        batch_op.drop_column('school_type')

    # ### end Alembic commands ###
